import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 420, height: 860 }, deviceScaleFactor: 2 })
await p.goto('http://localhost:5173/')
await p.fill('input[aria-label="Tên đăng nhập"]', 'e2e-user')
await p.fill('input[aria-label="Mật khẩu"]', 'pw12345678')
await p.click('button[type="submit"]')
await p.waitForTimeout(1500)
await p.click('text=Thiết bị')
await p.waitForTimeout(900)
await p.fill('input[aria-label="Mã 6 chữ số"]', '000000')
await p.fill('input[aria-label="Tên thiết bị"]', 'Thử sai')
await p.click('text=Ghép thiết bị')
await p.waitForTimeout(1300)
console.log('loi hien ra:', JSON.stringify((await p.textContent('[role="alert"]'))?.trim()))
console.log('con chu tieng Anh?', /invalid|expired|already paired|pairing code/i.test(await p.textContent('[role="alert"]') || ''))
await p.screenshot({ path: 'shots/dev-badcode.png' })
await b.close()
