import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 420, height: 860 }, deviceScaleFactor: 2 })
await p.goto('http://localhost:5173/')
await p.fill('#login-username', 'e2e-user')
await p.fill('#login-password', 'pw12345678')
await p.click('button[type="submit"]')
await p.waitForTimeout(1500)
// Pairing starts from an assistant now: Assistants -> a card's "Devices (n)"
// -> "+ Add device" -> the wizard. There is no standalone Devices tab.
await p.click('text=Assistants')
await p.waitForTimeout(900)
await p.locator('[data-act="devices"]').first().click()
await p.waitForTimeout(900)
await p.click('button:has-text("+ Add device")')
await p.click('button:has-text("I see a code")')
await p.waitForTimeout(300)
await p.fill('input[placeholder="00000000"]', '00000000')
await p.fill('input[placeholder="Name it, e.g. Kitchen speaker"]', 'Wrong on purpose')
await p.click('button:has-text("Pair device")')
await p.waitForTimeout(1300)
console.log('error shown:', JSON.stringify((await p.textContent('[role="alert"]'))?.trim()))
console.log('English message?', /invalid|expired|already paired|pairing code/i.test(await p.textContent('[role="alert"]') || ''))
await p.screenshot({ path: 'shots/dev-badcode.png' })
await b.close()
