import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 420, height: 860 }, deviceScaleFactor: 2 })
await p.goto('http://localhost:5173/')
await p.fill('input[placeholder="Username"]', 'e2e-user')
await p.fill('input[placeholder="Password"]', 'pw12345678')
await p.click('button[type="submit"]')
await p.waitForTimeout(1500)
await p.click('text=Devices')
await p.waitForTimeout(900)
await p.fill('input[placeholder="000000"]', '000000')
await p.fill('input[placeholder="Name it, e.g. Kitchen speaker"]', 'Wrong on purpose')
await p.click('button:has-text("Pair device")')
await p.waitForTimeout(1300)
console.log('error shown:', JSON.stringify((await p.textContent('[role="alert"]'))?.trim()))
console.log('English message?', /invalid|expired|already paired|pairing code/i.test(await p.textContent('[role="alert"]') || ''))
await p.screenshot({ path: 'shots/dev-badcode.png' })
await b.close()
