import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 420, height: 860 }, deviceScaleFactor: 2 })
const errors = []
p.on('pageerror', e => errors.push(String(e)))
await p.goto('http://localhost:5173/')
await p.fill('input[aria-label="Tên đăng nhập"]', 'e2e-user')
await p.fill('input[aria-label="Mật khẩu"]', 'pw12345678')
await p.click('button[type="submit"]')
await p.waitForTimeout(1500)
await p.click('button:has-text("Công cụ")')
await p.waitForTimeout(800)
const tabs = await p.locator('.nav__tabs button').allTextContents()
console.log('nav:', JSON.stringify(tabs))
await p.screenshot({ path: 'shots/tools-empty.png' })
await p.fill('textarea[aria-label="Đoạn chữ cần đọc"]', 'Xin chao, day la Lugo.')
await p.click('button:has-text("Đọc lên")')
await p.waitForTimeout(14000)
const src = await p.locator('audio').getAttribute('src').catch(()=>null)
console.log('audio src:', src)
console.log('TUYET DOI tro dung API?', String(src).startsWith('http://localhost:8000'))
const dur = await p.locator('audio').evaluate(a => a.duration).catch(()=>null)
console.log('duration (>0 = co tieng that):', dur)
const orange = await p.evaluate(() => [...document.querySelectorAll('.tool *')].filter(e => {
  const c = getComputedStyle(e); return /255,\s*138,\s*0/.test(c.backgroundImage + c.color)
}).length)
console.log('phan tu mau CAM (phai = 2 nut chinh):', orange)
await p.screenshot({ path: 'shots/tools-voice.png' })
console.log('loi trang:', errors.length ? errors : 'khong co')
await b.close()
